Adds support for MySQL publisher.
volkszaehler/mbmd pull request #348
Opened 2024-09-16 18:38 UTC by RatkoR

MySQL publisher stores measurements into `readings` table. Each value received is stored as a new record. Value description and unit name is also stored with each record. This means that table is denormalised but it's also faster and easier to use.

Publisher waits for all readings and inserts all values with one multiple INSERTs statement. This is way faster than saving each value separately.

2024-12-23 18:41 UTC, SchumacherFM requested changes

2024-12-23 18:41 UTC, SchumacherFM commented on server/mysql.go
> +				fmt.Println("Error preparing statement:", err)
IMHO: Please use `log...` everywhere.

2024-12-23 18:41 UTC, SchumacherFM commented on server/mysql.go
> +				fmt.Println("Nothing to do ...", time.Now().Unix())
IMHO: this will pollute the output with no valueable informatin. Remove it.

2024-12-23 18:41 UTC, SchumacherFM commented on server/mysql.go
> +			items = nil
IMHO: `items = items[:0]`

2024-12-23 18:41 UTC, SchumacherFM commented on server/mysql.go
> +			vals = nil
IMHO: `vals = vals[:0]`

2024-12-23 18:41 UTC, SchumacherFM commented on cmd/run.go
> +	}
IMHO: What if I want to connect to pgsql or sqlite or mssql? At least provide an adapter/interface where other developers can integrate their desired DB. Also the CLI args should be then: `db.type=mysql`, `db.host`, `db.user` and so on

2024-12-23 18:41 UTC, SchumacherFM commented on server/mysql.go
> +		panic(err.Error())
IMHO: Please no panic, return an error with proper information

2025-01-02 13:56 UTC, RatkoR commented
@SchumacherFM, thank you for looking at the pull request!

Comments are valid and easily fixed. Also, tests are missing. But I'd like to explain something before continuing:

I was running mbmd with MySQL publisher for two days. I queried solaredge every 10 seconds which collected more than a million values into db table. Running like this for a year (or more) would collect hundred of millions records which is very slow to query. And 10 seconds is not much. Querying every 2 seconds gathers 5x as many records.

So I added new parameters to limit which subset of fields are saved to db and which are skipped. This got me less records, but whatever parameter I needed at some point in future, I needed to add it to the list. It was skipped in previous queries, so I had no historical values for it. This proved to be less what I needed than I thought.

So maybe this is not such a great way to gather values. Prometheus or custom script through MQTT is probably better (which is what i did in the end).

Fill free to close the PR (or I'll do it later if nobody continues with it).

2025-01-03 07:56 UTC, SchumacherFM commented
@RatkoR Thanks for the nice comment :-) I can't close this PR because I'm not owner/maintainer.

> which collected more than a million values into db table.

You need to write an aggregator to build daily/weekly/monthly sums and then delete old values.

Or you can use my prometheus PR.

2025-01-03 08:47 UTC, RatkoR commented
Sure, aggregations are fine, but you need to fine-tune them. Some need daily, some monthly. Some weekly starting with Sunday, some weekly starting with Monday. Then there's timezone offset and yearly stats, ... Some need longer retention of original data than others, etc.

Looks to me we'd need a ton of parameters so that everybody can set their own preferable way. Otherwise they need to do cronjobs to aggregate and cleanup. And if they can do crons, they can probably do mqtt (or prometheus).

I'll see where my project takes me - I'll revisit this if I find a good cause to do it in MySQL natively.

2025-01-03 08:47 UTC, closed without merging

2025-01-03 09:13 UTC, SchumacherFM commented
The aggregation program does not belong into mbmd. This should be a 3rd party service. mbmd just provides/writes the raw data.